### ISSUE TITLE
move geom_line above geom_point

### ISSUE THREAD

**Issue by othomantegazza** [sapo83/TidyTuesday#1]
Hi, your tidy Tuesday `cleveland.dotplot.md` is great.

I have a couple of suggestions:

- If you move `geom_line()` above `geom_point()` the line will appear below the point  (I think it looks better this way but this is just my opinion).
- I would use `spread()` / `gather()` which are a bit more modern than `melt()` http://r4ds.had.co.nz/tidy-data.html#spreading-and-gathering
- you should move `size = 3` out of  `aes()` because you are setting the aesthetic, not mapping it. https://socviz.co/makeplot.html#mapping-aesthetics-vs-setting-them

Sorry for the intrusion, hope it helps, if you want I can send you a pull request.

Keep up the good work :)

**Comment by sapo83** [comment]
Thanks for the feedback! I didn't even notice the line over the dot. Great catch! I totally agree on using `spread()`/`gather()` instead of `melt()`. I spent a lot of time on cleaning the data for this one & `melt()` was my lazy side kicking in.  Also, moving size out of the `aes()` is a good call!

I would love if you would send a pull request. I've never done one & it would be great practice for me!

Thank you again for taking the time to look over my tutorial & offer suggestions!
